### ISSUE TITLE
Add option to disable website.

### ISSUE THREAD

**Issue by ChronoBrake** [dalexhd/SteamSpeak#120]
## 🚀 Feature

No everyone want to use website. One will use only server bot without website other can use all if want. I wanna use it on my server, but i already have dynamic website, i don't need second. If it will be in config way to disable it will be great!

### Have you read the [Contributing Guidelines on issues](https://github.com/dalexhd/steamspeak/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by dalexhd** [comment]
The verification process still needs the website, but the admin page could be optional... This can be a nice feature to integrate on the v0.8.0 version.

**Comment by dalexhd** [comment]
Hello @ChronoBrake 
I've been looking the current server/client code structure. To implement this feature, the client build would need to be conditioned by the server config, which is not practical and clean solution for the current Code-Base.

What you can do:
Add custom rules to your Nginx/Apache configuration. Nginx's example:
```
location ~ ^/(wp-admin|wp-login\.php) {
      allow 1.2.3.4;
      deny all;
}

Since there's not a clean way to implement this feature, the issue will be closed.
