### ISSUE TITLE
Add SteamSpeak features to documentation.

### ISSUE THREAD

**Issue by rafalohaki** [dalexhd/SteamSpeak#24]
It would be nice to know what exactly this SteamSpeak do before i install it.
Project seems to be something amazing but idk what it does.
I cant find info about it in documentation.

**Comment by dalexhd** [comment]
This project currently is in development stage.
You can see the version on the GitHub main page. Unless it reaches the 1.0.0 version, I don't recommend you to use it in production.

Now let me explain what does SteamSpeak do:
The main feature it's the Steam Rich Presence integration. This means that you can display your steam status on TeamSpeak.
Demo:  ![Imgur](https://i.imgur.com/ujRsWOb.gif)
Also, my plan is to add a lot of new functionalities for a TeamSpeak server.
Like Server Name change, welcome message etc...
And finally all of this will be controlled by a VueJS control panel.

**Comment by dalexhd** [comment]
Hi @rafalohaki 
I've added that info into the documentation page.
If you have any suggestions, feel free to comment below or to open a pull request.

**Comment by rafalohaki** [comment]
Thank you so much.
