### ISSUE TITLE
feat(new plugin): [Insert your title here]

### ISSUE THREAD

**Issue by Chionya** [dalexhd/SteamSpeak#278]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on issues](https://github.com/dalexhd/steamspeak/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

**Comment by dalexhd** [comment]
Closing as it does not include any data.
